# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_window.ui'
#
# Created: Tue Oct 22 22:39:09 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(953, 494)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(953, 494))
        MainWindow.setMaximumSize(QtCore.QSize(953, 494))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setAcceptDrops(False)
        MainWindow.setAccessibleDescription(_fromUtf8(""))
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(630, 10, 311, 441))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tableOfAllGoods = QtGui.QTableWidget(self.groupBox)
        self.tableOfAllGoods.setGeometry(QtCore.QRect(30, 30, 256, 281))
        self.tableOfAllGoods.setObjectName(_fromUtf8("tableOfAllGoods"))
        self.tableOfAllGoods.setColumnCount(2)
        self.tableOfAllGoods.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableOfAllGoods.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableOfAllGoods.setHorizontalHeaderItem(1, item)
        self.button_createGood = QtGui.QPushButton(self.groupBox)
        self.button_createGood.setGeometry(QtCore.QRect(80, 380, 151, 31))
        self.button_createGood.setObjectName(_fromUtf8("button_createGood"))
        self.dateTime_Good = QtGui.QDateTimeEdit(self.groupBox)
        self.dateTime_Good.setGeometry(QtCore.QRect(60, 410, 194, 22))
        self.dateTime_Good.setObjectName(_fromUtf8("dateTime_Good"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 101, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 320, 276, 52))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.line_goodPrice = QtGui.QLineEdit(self.widget)
        self.line_goodPrice.setObjectName(_fromUtf8("line_goodPrice"))
        self.horizontalLayout_2.addWidget(self.line_goodPrice)
        self.line_goodName = QtGui.QLineEdit(self.widget)
        self.line_goodName.setObjectName(_fromUtf8("line_goodName"))
        self.horizontalLayout_2.addWidget(self.line_goodName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.line_goodDate = QtGui.QLineEdit(self.widget)
        self.line_goodDate.setObjectName(_fromUtf8("line_goodDate"))
        self.horizontalLayout.addWidget(self.line_goodDate)
        self.line_goodCountry = QtGui.QLineEdit(self.widget)
        self.line_goodCountry.setObjectName(_fromUtf8("line_goodCountry"))
        self.horizontalLayout.addWidget(self.line_goodCountry)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 591, 411))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.button_addGoodInOrder = QtGui.QPushButton(self.groupBox_2)
        self.button_addGoodInOrder.setGeometry(QtCore.QRect(380, 240, 201, 31))
        self.button_addGoodInOrder.setObjectName(_fromUtf8("button_addGoodInOrder"))
        self.button_createOrder = QtGui.QPushButton(self.groupBox_2)
        self.button_createOrder.setGeometry(QtCore.QRect(210, 330, 131, 31))
        self.button_createOrder.setObjectName(_fromUtf8("button_createOrder"))
        self.dateTime_Order = QtGui.QDateTimeEdit(self.groupBox_2)
        self.dateTime_Order.setGeometry(QtCore.QRect(180, 370, 194, 22))
        self.dateTime_Order.setObjectName(_fromUtf8("dateTime_Order"))
        self.widget1 = QtGui.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(210, 250, 135, 74))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line_orderName = QtGui.QLineEdit(self.widget1)
        self.line_orderName.setObjectName(_fromUtf8("line_orderName"))
        self.verticalLayout.addWidget(self.line_orderName)
        self.line_orderCountry = QtGui.QLineEdit(self.widget1)
        self.line_orderCountry.setObjectName(_fromUtf8("line_orderCountry"))
        self.verticalLayout.addWidget(self.line_orderCountry)
        self.line_orderDilivery = QtGui.QLineEdit(self.widget1)
        self.line_orderDilivery.setObjectName(_fromUtf8("line_orderDilivery"))
        self.verticalLayout.addWidget(self.line_orderDilivery)
        self.widget2 = QtGui.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(20, 20, 524, 215))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.widget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.columnOrders = QtGui.QColumnView(self.widget2)
        self.columnOrders.setResizeGripsVisible(True)
        self.columnOrders.setObjectName(_fromUtf8("columnOrders"))
        self.verticalLayout_3.addWidget(self.columnOrders)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.widget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.columnGoodsInOrd = QtGui.QColumnView(self.widget2)
        self.columnGoodsInOrd.setResizeGripsVisible(True)
        self.columnGoodsInOrd.setObjectName(_fromUtf8("columnGoodsInOrd"))
        self.verticalLayout_4.addWidget(self.columnGoodsInOrd)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(610, -20, 20, 761))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.menu.addAction(self.action_Quit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Управление заказами", None))

        self.groupBox.setTitle(_translate("MainWindow", "Область товаров", None))
        item = self.tableOfAllGoods.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя товара", None))
        item = self.tableOfAllGoods.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Цена", None))
        self.button_createGood.setText(_translate("MainWindow", "Добавить товар в список", None))
        self.label_3.setText(_translate("MainWindow", "Список товаров", None))
        self.line_goodPrice.setText(_translate("MainWindow", "цена", None))
        self.line_goodName.setText(_translate("MainWindow", "Имя товара", None))
        self.line_goodDate.setText(_translate("MainWindow", "Дата произвадства", None))
        self.line_goodCountry.setText(_translate("MainWindow", "страна", None))

        self.groupBox_2.setTitle(_translate("MainWindow", "Область заказов", None))
        self.button_addGoodInOrder.setText(_translate("MainWindow", "Добавить выбранный товар в заказ", None))
        self.button_createOrder.setText(_translate("MainWindow", "Создать заказ", None))
        self.line_orderName.setText(_translate("MainWindow", "Имя заказа", None))
        self.line_orderCountry.setText(_translate("MainWindow", "Страна доставки", None))
        self.line_orderDilivery.setText(_translate("MainWindow", "Страна доставки", None))
        self.label.setText(_translate("MainWindow", "список заказов", None))
        self.label_2.setText(_translate("MainWindow", "Товары в заказе", None))
        self.menu.setTitle(_translate("MainWindow", "Меню", None))
        self.action_Quit.setText(_translate("MainWindow", "Выход", None))

